apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-backend-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: {{.Chart.Name}}-backend-app