apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 3000
  selector:
    app: {{.Chart.Name}}-frontend-app
